language: python

service:
  - docker

before_install:
- docker build . -t todo-app:test --target=test
- docker run -d -p 5000:5000 todo-app:test

before_script:
- cd /srv/www/todo_app/tests
script:  
- tdd_tests.sh
