language: python

service:
  - docker

before_install:
- docker build . -t todo-app:test 
- docker run --name travisImage -d -p 5000:5000 --mount type=bind,source=$(pwd)/,target=/srv/www todo-app:test
- docker ps -a

script:  
- docker exec -it travisImage echo 'Hello World'


