language: python

service:
  - docker

before_install:
- docker build . -t todo-app:test --target=test
- docker run -d -p 5000:5000 --env-file .env todo-app:test

script:
- pytest "/srv/www/todo_app/tests/function_tests.py
