service:
  - docker

before_install:
- docker build . -t todo-app:travis --target:travii
- docker run --name travisImage -it -p 5000:5000  todo-app:travis
- docker ps -a

script:  
- docker exec -it travisImage echo 'Hello World'


