language: python

service:
  - docker

before_install:
- docker build . -t todo-app:test 
- docker run -d --name travisImage -p 5000:5000 todo-app:test
- docker exec -it travisImage pytest "/srv/www/todo_app/tests/function_tests.py"
- docker ps -a

script:  
- ls -R


