language: python

service:
  - docker

before_install:
- docker build . -t todo-app:dev --target=development
- docker docker run -d -p 5000:5000 --mount type=bind,source=$(pwd)/todo_app,target=/srv/www todo-app:dev 

script:
- echo "hello world"
