language: python

service:
  - docker

before_install:
- docker build . -t todo-app:dev --target=development
- docker run -d -p 5000:5000 todo-app:dev --mount type=bind,source=$(pwd)/,target=/srv/www todo-app:dev 

script:
- /srv/www/todo_app/tests/testrunner.sh
