services:
  app-dev:   
   image: todo-app:dev
   ports:
     - "5000:5000"
   volumes:
     - ./todo_app:/srv/www/
   env_file:
   - .env
  selenium:
   image: selenium/standalone-chrome
   ports:
     - "4444:4444"
   

