FROM alpine as base

WORKDIR /tmp
CMD ["apk add busybox"]
EXPOSE 5000

FROM base as production
COPY prod-script.sh /tmp
RUN chmod +x /tmp/prod-script.sh && /tmp/prod-script.sh
ENTRYPOINT /srv/www/DevOps-Course-Starter/todo_app/applaunch.sh

FROM base as development 
COPY dev-script.sh /tmp
RUN chmod +x /tmp/dev-script.sh && /tmp/dev-script.sh
ENTRYPOINT ["/bin/sh"]
