name: Test Build

on:
  push:
    branches: [ module10 ]
  pull_request:
    branches: [ module10 ]

env: 
 dbpassword: ${{ secrets.DBPASSWORD }}
 slackuripram: ${{ secrets.SLACKURIPRAM }}
 oauthlib_insecure_transport: ${{ secrets.oauthlib_insecure_transport }}
 oauth_id: ${{ secrets.oauth_id }}
 oauth_secret ${{ secrets.oauth_secret }}

jobs:

  build:
     
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
       
    - name: Build the test Docker image
      run: docker build . -t todo-app:test --target=test 
    - name: Start the docker image
      run: docker run --name githubactionsImage -d -p 5000:5000 -e dbpassword --mount type=bind,source=$(pwd)/,target=/srv/www todo-app:test
    - name: Run some PyTests
      run: docker exec -t githubactionsImage "pytest" -p no:warnings /srv/www/todo_app/tests
   
